// Shared brand tokens for all auth email templates.
// Email body must always be white per Lovable guidelines.

export const BRAND = {
  name: 'Quiz EBD ADREC',
  trimester: '1º TRI. 2026 · ADREC',
  church: 'Assembleia de Deus em Recife',
  primary: '#4CC9E0',
  primaryDark: '#2BA8C0',
  dark: '#05070D',
  text: '#374151',
  muted: '#9CA3AF',
  border: '#E5E7EB',
  bgSoft: '#F1F8FA',
}

export const styles = {
  main: {
    backgroundColor: '#ffffff',
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif',
    margin: 0,
    padding: 0,
  },
  container: {
    maxWidth: '560px',
    margin: '0 auto',
    padding: '0',
  },
  header: {
    background: `linear-gradient(135deg, ${BRAND.dark} 0%, #0E1424 100%)`,
    backgroundColor: BRAND.dark,
    padding: '28px 24px 24px',
    borderRadius: '14px 14px 0 0',
    textAlign: 'center' as const,
  },
  brandTitle: {
    color: '#ffffff',
    fontSize: '20px',
    fontWeight: 700 as const,
    margin: '0 0 6px',
    letterSpacing: '0.3px',
  },
  brandBadge: {
    display: 'inline-block',
    backgroundColor: `${BRAND.primary}22`,
    color: BRAND.primary,
    fontSize: '11px',
    fontWeight: 700 as const,
    letterSpacing: '1.2px',
    textTransform: 'uppercase' as const,
    padding: '5px 12px',
    borderRadius: '999px',
    border: `1px solid ${BRAND.primary}55`,
  },
  body: {
    backgroundColor: '#ffffff',
    padding: '32px 28px 8px',
    border: `1px solid ${BRAND.border}`,
    borderTop: 'none',
  },
  h1: {
    fontSize: '22px',
    fontWeight: 700 as const,
    color: BRAND.dark,
    margin: '0 0 16px',
    textAlign: 'center' as const,
  },
  text: {
    fontSize: '15px',
    color: BRAND.text,
    lineHeight: '1.65',
    margin: '0 0 14px',
  },
  small: {
    fontSize: '12px',
    color: BRAND.muted,
    lineHeight: '1.5',
    margin: '16px 0 0',
  },
  link: {
    color: BRAND.primary,
    wordBreak: 'break-all' as const,
  },
  button: {
    backgroundColor: BRAND.primary,
    backgroundImage: `linear-gradient(135deg, ${BRAND.primary} 0%, ${BRAND.primaryDark} 100%)`,
    color: '#ffffff',
    padding: '14px 36px',
    borderRadius: '10px',
    fontSize: '16px',
    fontWeight: 700 as const,
    textDecoration: 'none',
    display: 'inline-block',
    boxShadow: `0 4px 14px ${BRAND.primary}55`,
  },
  code: {
    fontFamily: '"Courier New", Courier, monospace',
    fontSize: '34px',
    fontWeight: 700 as const,
    color: BRAND.dark,
    margin: '0',
    letterSpacing: '10px',
    backgroundColor: BRAND.bgSoft,
    border: `1px solid ${BRAND.primary}44`,
    borderRadius: '12px',
    padding: '22px 28px',
    display: 'inline-block',
  },
  hr: {
    borderColor: BRAND.border,
    margin: '28px 0 20px',
  },
  footer: {
    backgroundColor: '#FAFBFC',
    border: `1px solid ${BRAND.border}`,
    borderTop: 'none',
    borderRadius: '0 0 14px 14px',
    padding: '20px 24px',
    textAlign: 'center' as const,
  },
  footerText: {
    fontSize: '12px',
    color: BRAND.muted,
    margin: '0 0 6px',
    lineHeight: '1.6',
  },
  footerBrand: {
    fontSize: '12px',
    color: BRAND.dark,
    fontWeight: 600 as const,
    margin: '0',
  },
}
